name: Build and Release

on:
    workflow_dispatch:
        inputs:
            version:
                description: 'Version to release'
                required: true
                default: 'v1.0.0'

permissions:
  contents: write

jobs:
  build:
    if: github.actor == 'santrancisco'
    name: Build Binaries
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.16

      - name: Build binaries
        run: make build

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: bin/

  release:
    if: github.actor == 'santrancisco'
    name: Create Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download binaries
        uses: actions/download-artifact@v4
        with:
          name: binaries
          path: bin/

      - name: Create GitHub Release
        uses: ncipollo/release-action@440c8c1cb0ed28b9f43e4d1d670870f059653174 #v1.16.0
        with:
          artifacts: "bin/*"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.event.inputs.version }}
          name: Release ${{ github.event.inputs.version }}
          body: |
            This release contains the following binaries:
            - macOS (arm64)
            - Windows (amd64)
            - Linux (amd64)
